meokda_community/meokda_community/urls.py
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from django.urls import path, include


from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')), 
    path('video/', include('video.urls')),
    path('',RedirectView.as_view(pattern_name='video:video_list'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meokda_community/user/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
    path('register/', views.register),
    path('login/', views.login),
    path('logout/', views.logout),
    path('about/', views.about),
]

meokda_community/video/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.


class Video(models.Model):
    status_choices = {
      ('before eating', '먹기전'),  # 오른쪽에 있는 것이 화면에 보인다.
      ('eating', '먹는중'),
  }

    restaurant = models.CharField(max_length = 128, verbose_name = '가게이름')
    foodname = models.CharField(max_length= 128, verbose_name= '음식이름')
    file = models.FileField()

    price = models.PositiveIntegerField(default=0)
    status =  models.CharField(max_length=80, choices= status_choices, null=True)
    distance = models.PositiveIntegerField(default=0, verbose_name='거리')


    title = models.CharField(max_length= 128, verbose_name= '제목', default= '모르겠어요')
    author = models.ForeignKey('user.meokda_user', on_delete = models.CASCADE, verbose_name = '작성자', null = True )
    created_at = models.DateTimeField(auto_now_add = True, verbose_name = '등록시간')
    updated_at = models.DateTimeField(auto_now = True)

    def get_absolute_url(self):
        return reverse('video:video_list')
    
    class Meta:
      ordering = ['-created_at']



class Article(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField(max_length=2000)
    date = models.DateTimeField()
    author = models.CharField(max_length=30)
    file = models.FileField(null=True)

meokda_community/templates/form.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="/static/bootstrap.min-4.css">

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/">Meokda</a>



      <form class="form-inline  my-lg-0  d-flex justify-content-center align-items-center container">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary " type="submit">검색</button>
      </form>


      <button type="button" class="btn btn-info mr-5" style="white-space:nowrap; "
        onclick="location.href = '/video/new'">글쓰기</button>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user/logout">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user/about">About</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#"> {{ authoring }}232</a>
        </li>
      </ul>


  </nav>



<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table> 
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>

</body>


</html>

meokda_community/templates/form2.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="/static/bootstrap.min-4.css">
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <!-- Style -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <link rel="stylesheet" href="/static/bootstrap.min-4.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Quicksand'><link rel="stylesheet" href="{% static 'mithril-1-0-file-uploader/dist/style2.css' %}">

  <title>Meokda 로그인</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/">Meokda</a>



      <form class="form-inline  my-lg-0  d-flex justify-content-center align-items-center container">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary " type="submit">검색</button>
      </form>


      <button type="button" class="btn btn-info mr-5" style="white-space:nowrap; "
        onclick="location.href = '/video/new'">글쓰기</button>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user/logout">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user/about">About</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#"> {{ authoring }}232</a>
        </li>
      </ul>


  </nav>

  <div class="d-lg-flex half">
    <div class="bg order-1 order-md-2">
      <div id="uploader"></div>
    </div>
    <div class="contents order-2 order-md-1">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-7">
            <div class="mb-5">
              <h1>동영상 올리기</h1>
              <p class="mb-5">먹고 싶은거 다 있다. 먹다</p>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group last mb-4">
                {% if field.name == 'file' or field.name == 'status' %}
                <label for="{{ field.id_for_label }}"></label>

                {% else %}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% endif %}
                
                {% if field.name == 'status' %}
                <select type="{{ field.field.widget.input_type }}" name="status" class ="form-control" id="id_status">
                  <option value="status_choices">상태</option>
                  <option value="before eating">먹기전</option>
                  <option value="eating">먹는중</option>
              </select>
                
                {% else %}
                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
                name="{{ field.name }}" />

                {% endif %}

               
              </div>
              
              {% if field.errors %}
              <span style="color : red">{{ field.errors }} </span>
              {% endif %}
              {% endfor %}

              <input type="submit" value="발행하기" class="mt-5 btn btn-block btn-primary">
            
            </form>
          </div>
        </div>
      </div>
    </div>


  </div>
  <script src='https://cdn.rawgit.com/lhorie/mithril.js/rewrite/mithril.js'></script><script  src="{% static 'mithril-1-0-file-uploader/dist/script.js'%}"></script>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>


</html>