meokda_community/meokda_community/urls.py
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from django.urls import path, include


from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')), 
    path('video/', include('video.urls')),
    path('',RedirectView.as_view(pattern_name='video:video_list'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meokda_community/user/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
    path('register/', views.register),
    path('login/', views.login),
    path('logout/', views.logout),
    path('about/', views.about),
]

meokda_community/video/urls.py
from django.urls import path
from . import views
from .models import Video

from django.conf.urls import url

app_name = 'video'

urlpatterns = [ 
    path('',views.VideoListView.as_view(), name='video_list'),
    path('new/', views.VideoCreateView.as_view(), name = 'video_new'),
    path('<int:pk>/',views.VideoDetailView.as_view(), name = 'video_detail'),
    path('<int:pk>/edit/',views.VideoDetailView.as_view(), name = 'video_edit'),
    path('<int:pk>/delete/',views.VideoDeleteView.as_view(), name = 'video_delete'),
    path('index/',views.index),
    path('test/',views.ArticlesView.as_view(), name='articles'),


]

meokda_community/video/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.


class Video(models.Model):
    status_choices = {
      ('before eating', '먹기전'),  # 오른쪽에 있는 것이 화면에 보인다.
      ('eating', '먹는중'),
  }

    restaurant = models.CharField(max_length = 128, verbose_name = '가게이름')
    foodname = models.CharField(max_length= 128, verbose_name= '음식이름')
    file = models.FileField()

    price = models.PositiveIntegerField(default=0)
    status =  models.CharField(max_length=80, choices= status_choices, null=True)
    distance = models.PositiveIntegerField(default=0, verbose_name='거리')


    title = models.CharField(max_length= 128, verbose_name= '제목', default= '모르겠어요')
    author = models.ForeignKey('user.meokda_user', on_delete = models.CASCADE, verbose_name = '작성자', null = True )
    created_at = models.DateTimeField(auto_now_add = True, verbose_name = '등록시간')
    updated_at = models.DateTimeField(auto_now = True)

    def get_absolute_url(self):
        return reverse('video:video_list')
    
    class Meta:
      ordering = ['-created_at']



class Article(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField(max_length=2000)
    date = models.DateTimeField()
    author = models.CharField(max_length=30)
    file = models.FileField(null=True)

meokda_community/video/forms.py
from django import forms
from .models import Video
import os

class VideoForm(forms.ModelForm):
    def clean_file(self):
        file = self.cleaned_data.get('file', None)
        if file:
            extension = os.path.splitext(file.name)[-1].lower()
            if extension not in ('.mp4', '.avi', '.mov','.MP4','.MOV','.AVI'):
                raise forms.ValidationError('비디오파일을 올려주세요')
            return file


    class Meta:
        model = Video
        fields = [
            'restaurant',
            'foodname',
            'file',
            'price',
            'status',
            'distance',
        ]

meokda_community/video/views.py
from django.db.models.query_utils import select_related_descend
from django.shortcuts import render,redirect
from .models import Video
from .forms import VideoForm
from django.views.generic import ListView, DeleteView, DetailView,CreateView,UpdateView 
from user.models import meokda_user
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.utils.decorators import method_decorator
from user.decorators import login_required
from django.urls import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# import simplejson as json
# from rest_framework import generics
# from rest_framework.pagination import PageNumberPegination
# Create your views here.


class VideoListView(ListView):
    model = Video
    paginate_by = 4
    context_object_name = 'video_list'
    template_name = 'video/video_list.html'

def index(request):
    return render(request, 'index.html', {'username' : request.session.get('user')})


@method_decorator(login_required, name='dispatch')
class VideoCreateView(CreateView):
    model = Video
    form_class = VideoForm
    template_name = 'form2.html'


    def form_valid(self, form):
        video = form.save(commit=False)
        user_id = self.request.session.get('user')
        meokdauser = meokda_user.objects.get(username = user_id)
        video.author = meokdauser
        return super().form_valid(form)
    
    # success_url = '/'


class VideoDetailView(DetailView):
    model = Video


class VideoUpdateView(UpdateView):
    model = Video
    form_class = VideoForm
    template_name = 'form.html'


class VideoDeleteView(DeleteView):
    model = Video
    success_url = reverse_lazy('video:video_list')


from django.views.generic.list import ListView
from .models import Article

class ArticlesView(ListView):
    model = Article
    paginate_by = 5
    context_object_name = 'videos'
    template_name = 'video/articles.html'

meokda_community/video/templates/video/articles.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="/static/bootstrap.min-4.css">
  {% load static %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
 <script src="{% static 'js/infinite.min.js' %}"></script>
</head>

<body>
  
<div class="infinite-container">
  {% for article in videos reversed%}
    <div class="infinite-item">
      <h3>{{ article.title }}</h3>
      <video class="center align-middle" controls muted autoplay loop style='max-width: 100%; max-height: 700px;'>
        <source src="{{ article.file.url }}" type="video/mp4">
        Your browser does not support the video tag.
      </video>
      </video>
      <p>
        <small>{{ article.author }} / {{ article.date }}</small>
      </p>
      <p>{{ article.body|truncatechars:100 }}</p>
    </div>
  {% endfor %}
</div>

<div class="loading" style="display: none;">
  Loading...
</div>

{% if page_obj.has_next %}
  <a class="infinite-more-link" href="?page={{ videos.next_page_number }}">More!</a>
{% endif %}

<script>
  var infinite = new Waypoint.Infinite({
    element: $('.infinite-container')[0],
    onBeforePageLoad: function () {
      $('.loading').show();
    },
    onAfterPageLoad: function ($items) {
      $('.loading').hide();
    }
  });
</script>
</body>


</html>

meokda_community/video/templates/video/new_video.html
dsfd

meokda_community/video/templates/video/video_confirm_delete.html
정말 삭제하실래요?

<form action = '' method = 'POST'>
    {% csrf_token %}    
    <input type = "submit" value = "삭제" />

</form>

meokda_community/video/templates/video/video_delete.html
fuckou

meokda_community/video/templates/video/video_detail.html
fuck 1

meokda_community/video/templates/video/video_list.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="/static/bootstrap.min-4.css">
  {% load static %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/infinite.min.js' %}"></script>
  {% load humanize %}
</head>

<body>
  <section style = 'position: fixed; z-index:666;top:0; right: 0; left:0;'>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-5">
    <div class="container">
      <a class="navbar-brand" href="/">Meokda</a>



      <form class="form-inline  my-lg-0  d-flex justify-content-center align-items-center container">
        <input class="form-control mr-sm-2" type="text" placeholder="제작지원 - 조코딩 유튜브채널">
        <button type='button' class="btn btn-secondary " onclick=" location.href = 'https://www.youtube.com/channel/UCQNE2JmbasNYbjGAcuBiRRg'">
          이동</button>
      </form>


      <button type="button" class="btn btn-info mr-5" style="white-space:nowrap; "
        onclick="location.href = '/video/new'">글쓰기</button>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home
          </a>
        </li>
        {% if request.session.user %}


        <li class="nav-item">
          <a class="nav-link" href="/user/about">About</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#"> {{ request.session.user }} </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user/logout">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/user/login">Login</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/user/about">About</a>
        </li>
        {% endif %}
      </ul>


  </nav>
</section>
<div style ='height:75px;'>

</div>

  <div class="container text-center infinite-container">


    {% for video in video_list %}
    <div class="card text-center mt-5 infinite-item">

      <div> {{video.author }}
        {% if request.session.user == 'gkuer' %}

        <button class="btn btn-info" onclick="location.href = '{% url 'video:video_delete' video.pk %}'">삭제</button>

        {% else %}
        video{{ video.id }}
        {{ video.pk }}
        {{ video.self.pk }}
        {{ video.self.id }}

        dd
        {% endif %}
      </div>
      <div class="card-header bg-transparent">
        <div class="row">
          <a class="nav-link navbar-brand  text-muted mr-0" href="#">
            <h4>{{video.restaurant}}</h4>
          </a>
          <a class="nav-link navbar-brand  text-muted ml-0 mt-1" href="#"><small>{{video.distance}}km</small></a>

          <a class="nav-link  navbar-brand  text-muted ml-auto" href="#">{{video.author}}</a>
          </li>
        </div>

        <div class="row">
          <a class="nav-link navbar-brand  text-muted mr-0" href="#">{{video.foodname}}</a>
          <a class="nav-link navbar-brand  text-muted ml-0 mt-1" href="#"><small>{{video.price | intcomma}}원</small></a>

          <a class="nav-link navbar-brand  ml-auto text-muted" href="#">{{video.get_status_display }}</a>
        </div>

      </div>


      <div class="card-body" style="padding:0;">
        <video id='video{{video.id}}' class="video center align-middle" controls="true" autoplay muted loop playsinline
          style='max-width: 100%; max-height: 700px;' onclick="unmute('video{{video.id}}')">
          <source src="{{ video.file.url }}" type="video/mp4">
          </source>

          Your browser does not support the video tag.
        </video>


        <script>
          function unmute(self) {
            const player = document.getElementById(self);

            if (player.muted) {
              player.muted = false;

            }
            else {
              player.muted = true;

            }
            if (player.pause()) {
              player.play();
            }
          }
          $(function () {

            var $video = $('#video{{video.id}}');
            var $window = $(window);

            $window.scroll(function () {

              var $topOfVideo = $video.offset().top;
              var $bottomOfVideo = $video.offset().top + $video.outerHeight();

              var $topOfScreen = $window.scrollTop();
              var $bottomOfScreen = $window.scrollTop() + $window.innerHeight();

              if (($bottomOfScreen > $bottomOfVideo) && ($topOfScreen < $topOfVideo)) {
                $video[0].play();
              } else {
                $video[0].pause();
              }

            });

          });
        </script>


      </div>
    </div>

    {% endfor %}

  </div>

  <div class="loading" style="display: none;">
    Loading...
  </div>

  {% if page_obj.has_next %}
  <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">More</a>
  {% endif %}

  <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],

      onBeforePageLoad: function () {
        $('.loading').show();
      },
      onAfterPageLoad: function ($items) {
        $('.loading').hide();
      }
    });
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>


</body>


</html>